name: Run Telegram Bot

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 */5 * * *'  # Run every 5 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # Run for 5 hours (almost max allowed)
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot[job-queue] pytz
        
    - name: Run bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: python main.py
